name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [21, 17]
        include:
          - base-image: inseefrlab/onyxia-vscode-python:py3.11.6
            destination-image: odysseu/onyxia-vscode-java
            dockerfile: vscode-java/Dockerfile
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build & Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.destination-image }}:j${{ matrix.tag }}
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
            JAVA_VERSION=${{ matrix.tag }}
